def icu_agent_rule(obs):
    """
    Rule-based agent for Intensive Care Unit (ICU) resource allocation.

    The rule is: Allocate an ICU bed if and only if there is at least one 
    free bed AND at least one critical patient waiting for the ICU.

    :param obs: The current observation dictionary from the HospitalDT environment.
    :return: An action dictionary: {'allocate_icu': boolean}.
    """
    # Action is True if: (ICU beds available > 0) AND (ICU waiting queue length > 0)
    return {'allocate_icu': obs['icu_free'] > 0 and obs['icu_wait'] > 0}

def ot_agent_rule(obs):
    """
    Rule-based agent for Operating Theater (OT) resource allocation.

    The rule is: Allocate an OT unit if and only if there is at least one 
    free OT unit AND at least one patient waiting for surgery.

    :param obs: The current observation dictionary from the HospitalDT environment.
    :return: An action dictionary: {'allocate_ot': boolean}.
    """
    # Action is True if: (OT units available > 0) AND (OT waiting queue length > 0)
    return {'allocate_ot': obs['ot_free'] > 0 and obs['ot_wait'] > 0}

def staff_agent_rule(obs):
    """
    Rule-based agent for staff reassignment/management (placeholder action).

    The rule is: Reassign staff (e.g., from non-critical tasks to the ED) 
    if the Emergency Department (ED) waiting queue is excessively long (length > 5).

    :param obs: The current observation dictionary from the HospitalDT environment.
    :return: An action dictionary: {'reassign_staff': boolean}.
    """
    # Check if the ED waiting queue length exceeds the threshold of 5
    if obs['ed_wait'] > 5:
        return {'reassign_staff': True}
    return {'reassign_staff': False}

def merge_actions(*actions):
    """
    Combines the action dictionaries generated by individual agents into a single 
    dictionary that the HospitalDT environment's `step` method accepts.

    :param actions: A variable number of action dictionaries (e.g., a1, a2, a3).
    :return: A single merged action dictionary.
    """
    res = {}
    for a in actions:
        # Use the update() method to merge key-value pairs from each dictionary
        res.update(a)
    return res